
spring:
  cloud:
    config:
      uri: http://localhost:8888
  application:
    name: greeting-client

#mtls:
# keystore:
#   password: password
#   value: |
#    /u3+7QAAAAIAAAABAAAAAQAGdG9tY2F0AAABY6kg1o8AAAUBMIIE/TAOBgorBgEE
#    ASoCEQEBBQAEggTp23tFSJx2y+s6JSzIVYktZGTFq0NOijsq5wy/sUdiD5VnJnMc
#    K8Czp2l93AaxWi9tn05cA+GpNM4/KbQzAOrS9jxj4nwI8Pp/WjpJl6WRyGJ+iFH0
#    u1aL1s+fZIKGc2ejf02hZZO7FjXRWhai5Gulb7Oz6wburiUH3EJ78PJPd1UdAAZP
#    QCkxoQUCXIb357B2E0n3aMY1eZOQr52h4emwp8zqEeAeUTsnTdpA+vZACBAv9Tu7
#    1Y0ptON8/yk4nS1ue3dvMjBrU10R0rlOPPcwoJXhYEIkY6ZD1UDBCv7kYRP8tTh4
#    Tij6ahnY6MAGsLQ1ptQ0fKdur7gI5udBBygWpS8ves3EYWwyJfekbKFDR7Rj5hQc
#    8VHvuQXZObW1KZCpHTiGdR/5w51p7WKs+GDr0TVryOESe4w5mIarm8TU/w0yWRzs
#    S9K+ydkTgSYjE/0S5Cc1esj4pSiC/tZBNrcpo77oWEGjXfBjfkbjlOFjQWki4m4j
#    afWwalPVcNuKW3VVKNg4Qz1fhUfotrD5zWhwHV7L8OCocV+oYgcpr6CLWe666WYD
#    jXKDaAM2KN9aaIjBrIBaW/gbJXP8ucR/kXW8jX8oDIPNW00z/QPLjWvvHB1BwaHj
#    M23dL8PvyYpMREeAU/j9/htJKVvI8KIQq/0hsJjyVodC4YPIBy+zjLyibROznjNn
#    GoRQR0NU4ktlRqL9CZU9MynfWXSjmmBBPYx8uvsKz/WDLUjuFpvSMTgsXPx6A1j9
#    t3i6xcYOfsyP5mtRhwk6HD4pFnB11IyYsEzb8W2odolwQ1vehHD3sDK+3srlKx2G
#    P1nvbsw7U0dFfe6swFnrcG5gva6OXdIxP/viYwPIbNEbP6/E0ZmnoP8N9xq4Y85h
#    qAxzv50qIk20HoRW4STi5bYliJi5fzYO0IezCt1FVnELP9FuF7PPMB5U1njqqBQE
#    8jXJkyZo0StyESrxRgfDjeysPlcPG3z+315/Q2mHlm+NTpo00VPoWGZySrqmFfW2
#    CIglZYPZqmvxeahzQfQqs0KvBFRz4kMSXeI8zAioxkYPOmiXu9JvGmwZ2/aMaywb
#    EcO3L7vX9tAOqYnzXPwYvxvjL2/lhGeydm5hxtAirGutG9tkfLeYlo8EjzKjug4R
#    aJog9DQwue2vSricxNue45f7R3Gau1t6Quqk21E2iLg6iczLjCzWLPaHfHoNsL3A
#    M+nzlldVNXsYpAq9qlnQ5bC+6Es3iz/BKlq0sFLUr5T/7mxNQ5hhmxCuxzXYQfru
#    mOErTRIEK2UoYskdyLdSoPIGtP0NM56XTnN+JAWJZOaUiMYA0KADrOoZNETlenwm
#    troY4SJfiewoAGKRUURRfNE788tqoNIWissKTvfBOpMs2x9woHMvNrnoDVfjBMpb
#    PFksBweyZaoKTqTbrDaRgFcid9ziUlP5MVjkOvrWXHFkqReRZNf1hw9Cg1uEO/o7
#    bKXCQ5Vzrz/5oDjpcAj1pTWX7ysoU01mNfzOScRRk73VloX+pkEyRPJVB+eoBHJK
#    pk81F2XTVcoKrARRm/Ugvn+Rk1k4t3tn+bVIQhDDBcSjwuB1GvCo/xm95CdPwlpC
#    1+wiccC40FOOcHbe21j+kQfrkCedyP/sgrqyor1GamjpUbYzJlRWo537lA3gmyYI
#    x0tm8rzlCXJ0lkuN2tc1lXrKnBPhAAAAAQAFWC41MDkAAAN5MIIDdTCCAl2gAwIB
#    AgIEOQoxOTANBgkqhkiG9w0BAQsFADBrMQswCQYDVQQGEwJDQTELMAkGA1UECBMC
#    T04xEDAOBgNVBAcTB1Rvcm9udG8xEDAOBgNVBAoTB0V4YW1wbGUxFDASBgNVBAsT
#    C0V4YW1wbGUgT3JnMRUwEwYDVQQDEwxBZGliIFNhaWthbGkwHhcNMTgwNTI4MjM0
#    MTE2WhcNMjgwNTI1MjM0MTE2WjBrMQswCQYDVQQGEwJDQTELMAkGA1UECBMCT04x
#    EDAOBgNVBAcTB1Rvcm9udG8xEDAOBgNVBAoTB0V4YW1wbGUxFDASBgNVBAsTC0V4
#    YW1wbGUgT3JnMRUwEwYDVQQDEwxBZGliIFNhaWthbGkwggEiMA0GCSqGSIb3DQEB
#    AQUAA4IBDwAwggEKAoIBAQCVz2t1ApFMqTTD+DuXfTPSdhZWtOFFQQ7Mb3hZR+AS
#    WUXiW3u/sGUBM+oZvvTXciG/69yj+7AlF0uWY2LoevTqwNGWF7dBSkvwoZQk9Usp
#    S9MfaNGlEUCkZz0EM7vTmzMyLPujJhNtjujycwoV9rILW00SL6gJG/W+QTGfsqWn
#    MZj/Lp9C0Iw6oVAWJMKTjzIFeYqZQu4pN96mjUvb8LdYiDLbwK/vtZKyyHnAr2yi
#    2mEI9S8H7WSHT+USM+dQVskbnLavpkGNQdlFWVC/mTiaLiXJKoI+upYGrZutzyRw
#    n6/onAKycpdwnsREFeahH2O7WLbEnseYcBSgDSa+GT0vAgMBAAGjITAfMB0GA1Ud
#    DgQWBBT4tXT0Ky7NnHOCKG/jZfHMtP7EIDANBgkqhkiG9w0BAQsFAAOCAQEACGOo
#    10ANbXgBdt17zdhd+CmszxFe2djIdotuC7QKWElCVPJDQ8q6BhvA63gXvsDX+A8x
#    tBMOq2s6lLD39JVAf9KcNVv6hJrJ9OxDm0WOOODxX7zlQgbmywFl7TD/RLGlwK8X
#    94vhiskniM2Ozx6LnNtGi4LZl3w69xg6ENpFkYuUCOzc81+q1rJBPKJ8e6JRU6V7
#    YhhqBObZ8YV5DSUVAETzdPy/Qf9yC9N/iScrR+93bWXdVBRm8XrYzk8HzJ2CG2DQ
#    JlxCkgI1haLMG163t8g+6lRdIVguZA3sSZrD/25s/kfBMZ1fIvh+iZBbHi8YCAOD
#    iqfJqIdtGUku6o2lc+Ybmo38PaAf1m0HGtNpATQSccJF