server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: "classpath:keystore.p12"
    key-store-password: password
    key-alias: tomcat
    client-auth: want
security:
  require-ssl: true


